name: Flat

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '10 */4 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: Install CA certificates
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates
          sudo update-ca-certificates

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: execute py script
        # bring in your MS_TOKEN, force-refresh flag,
        # plus a JSON proxy object for BrightData
        env:
          MS_TOKEN: ${{ secrets.MS_TOKEN }}
          FORCE_LAST_REFRESH: '1'
          PROXY: '{"server":"http://brd.superproxy.io:33335","username":"${{ secrets.BRIGHTDATA_USERNAME }}","password":"${{ secrets.BRIGHTDATA_PASSWORD }}"}'
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

          python3.12 -m venv venv
          source venv/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV

          pip install --upgrade pip
          pip install playwright==1.40.0
          pip install -r requirements.txt

          sudo apt-get update
          python -m playwright install-deps
          python -m playwright install

          python postprocessing.py

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --allow-empty -m "Latest TikTok RSS"
          git push
