# flat.yml
name: Flat

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '10 */4 * * *'

jobs:
  scheduled:
    # Use Ubuntu 22.04 to match Playwright's expected package versions
    runs-on: ubuntu-22.04

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: execute py script
        # inject your TikTok API & BrightData creds here
        env:
          MS_TOKEN:            ${{ secrets.MS_TOKEN }}
          FORCE_LAST_REFRESH:  '1'
          BRIGHTDATA_USERNAME: ${{ secrets.BRIGHTDATA_USERNAME }}
          BRIGHTDATA_PASSWORD: ${{ secrets.BRIGHTDATA_PASSWORD }}
          # BrightData rotating residential proxy endpoint:
          TIKTOK_PROXY:       "http://${{ secrets.BRIGHTDATA_USERNAME }}:${{ secrets.BRIGHTDATA_PASSWORD }}@brd.superproxy.io:33335"
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

          python3.12 -m venv venv
          source venv/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV

          pip install --upgrade pip
          pip install playwright==1.40.0
          pip install -r requirements.txt

          # make sure apt has up-to-date package lists
          sudo apt-get update

          # install all OS-level deps Playwright needs (GStreamer, libsoup, etc)
          python -m playwright install-deps

          # then fetch the browsers themselves
          python -m playwright install

          # run your feed generator (it will read $TIKTOK_PROXY automatically)
          python postprocessing.py

          # commit & push any new feeds/videos
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --allow-empty -m "Latest TikTok RSS"
          git push
